import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { TesseractEngine } from '../../src/workers/content-index/ocr-engine'

/**
 * The fixture set from PLAN.md §8, with expectations taken from what the engine actually reads —
 * measured first, written down second.
 *
 * Every image is generated by `scripts/make-ocr-fixtures.mjs` from invented text; no real message,
 * number or screenshot enters this repository (CLAUDE.md).
 *
 * The expectations are deliberately about *content that must be findable*, not about exact strings.
 * OCR is probabilistic: pinning the output character for character would produce a test that fails
 * on a tesseract upgrade without anything having got worse. What must hold is that searching for
 * the amount, the street or the city finds the picture.
 */

const tessdataDir = join(process.cwd(), 'resources', 'tessdata')
const fixture = (name: string): string => join(process.cwd(), 'test', 'fixtures', name)
const engine = new TesseractEngine({ tessdataDir })

const TIMEOUT = { timeout: 180_000 }

afterAll(async () => {
  await engine.close()
})

describe('OCR against the fixture set', () => {
  it('reads a chat screenshot', TIMEOUT, async () => {
    const result = await engine.extract(fixture('ocr-screenshot.png'))
    const text = result.text.toLowerCase()

    expect(text).toContain('rechnung')
    expect(text).toContain('münchen')
    expect(text).toContain('lieferung')
    expect(result.lines.length).toBeGreaterThan(2)
  })

  it('loses a light-on-green outgoing bubble, and that is worth knowing', TIMEOUT, async () => {
    // Measured, not assumed: the outgoing bubble's low-contrast text does not survive recognition
    // at this size. Recorded rather than papered over — it means a search for an amount that only
    // ever appeared in an outgoing screenshot can genuinely come up empty, and somebody debugging
    // that later should find this test rather than a mystery.
    const result = await engine.extract(fixture('ocr-screenshot.png'))
    expect(result.text).not.toContain('Klar, kommt gleich')
  })

  it('reads a dense invoice including the amounts and the umlauts', TIMEOUT, async () => {
    const result = await engine.extract(fixture('ocr-rechnung-dicht.png'))
    const text = result.text.toLowerCase()

    expect(text).toContain('küchenmöbel')
    expect(text).toContain('straßenweg')
    expect(text).toContain('1.249,90')
    expect(text).toContain('2026-0815')
    // Every line item's total, which is the thing anybody searching an invoice is after.
    for (const amount of ['698,00', '388,50', '113,40']) expect(result.text).toContain(amount)
  })

  it('gets small type slightly wrong without losing the line', TIMEOUT, async () => {
    // "Arbeitsplatte Eiche geölt" comes back as "gedit" at 13px. The row is still found, which is
    // what matters — and the failure mode is a wrong word, not a dropped line.
    const result = await engine.extract(fixture('ocr-rechnung-dicht.png'))
    expect(result.text).toContain('Arbeitsplatte Eiche')
  })

  it('reads a photographed whiteboard at an angle', TIMEOUT, async () => {
    const result = await engine.extract(fixture('ocr-whiteboard.png'))
    const text = result.text.toLowerCase()

    expect(text).toContain('sprint 14')
    expect(text).toContain('dachdecker')
    expect(text).toContain('schäfer')
    expect(text).toContain('rückfrage')
  })

  it('reads a document photographed off-axis', TIMEOUT, async () => {
    // Perspective, warm light, soft edges — what a phone camera actually produces.
    const result = await engine.extract(fixture('ocr-schraeg.png'))
    const text = result.text.toLowerCase()

    expect(text).toContain('übergabeprotokoll')
    expect(text).toContain('straßenweg')
    expect(text).toContain('48291')
  })

  it('reports confidence on a 0–1 scale, not a percentage', TIMEOUT, async () => {
    // The UI multiplies by 100 to show it. It once did not, and a 91 %-confident line was
    // displayed as "1 % sicher".
    const result = await engine.extract(fixture('ocr-schraeg.png'))
    expect(result.confidence).toBeGreaterThan(0)
    expect(result.confidence).toBeLessThanOrEqual(1)
    for (const line of result.lines) {
      expect(line.confidence ?? 0).toBeLessThanOrEqual(1)
    }
  })

  it('gives every line a box, so a hit can point into the image', TIMEOUT, async () => {
    const result = await engine.extract(fixture('ocr-whiteboard.png'))
    for (const line of result.lines) {
      expect(line.box).toBeDefined()
      const [x0, y0, x1, y1] = line.box ?? [0, 0, 0, 0]
      expect(x1).toBeGreaterThan(x0)
      expect(y1).toBeGreaterThan(y0)
    }
  })
})
