import { join } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { TesseractEngine } from '../../src/workers/content-index/ocr-engine'

/**
 * Real recognition against a rendered fixture. The image is generated by
 * `scripts/make-ocr-fixture.mjs` from invented text — no real message, number or screenshot ever
 * enters the repository (CLAUDE.md).
 */

const tessdataDir = join(process.cwd(), 'resources', 'tessdata')
const fixture = join(process.cwd(), 'test', 'fixtures', 'ocr-rechnung.png')
const engine = new TesseractEngine({ tessdataDir })

afterAll(async () => {
  await engine.close()
})

describe('TesseractEngine', () => {
  it('finds the bundled language data', async () => {
    expect(await engine.isAvailable()).toBe(true)
  })

  it('reports itself unavailable rather than failing per image when a model is missing', async () => {
    // A missing model is permanent; the queue must skip, not retry three times per picture.
    const broken = new TesseractEngine({ tessdataDir: '/nope' })
    expect(await broken.isAvailable()).toBe(false)
  })

  it('reads German text including umlauts and ß', { timeout: 120_000 }, async () => {
    const result = await engine.extract(fixture)
    const text = result.text.toLowerCase()

    expect(text).toContain('rechnung')
    expect(text).toContain('münchen')
    expect(text).toContain('straßenweg')
    expect(text).toContain('1.249,90')
  })

  it(
    'returns lines with boxes, so a hit can point at the place it came from',
    { timeout: 120_000 },
    async () => {
      const result = await engine.extract(fixture)
      const line = result.lines.find((l) => l.text.toLowerCase().includes('rechnung'))

      expect(line?.box).toBeDefined()
      const [x0, y0, x1, y1] = line?.box ?? [0, 0, 0, 0]
      expect(x1).toBeGreaterThan(x0)
      expect(y1).toBeGreaterThan(y0)
    },
  )

  it(
    'records engine, version and confidence for re-indexing later',
    { timeout: 120_000 },
    async () => {
      const result = await engine.extract(fixture)
      expect(result).toMatchObject({ source: 'ocr', engine: 'tesseract', lang: 'deu+eng' })
      expect(result.engineVersion).toMatch(/\d+\.\d+/)
      expect(result.confidence).toBeGreaterThan(0.5)
    },
  )
})
