import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { PdfEngine } from '../../src/workers/content-index/pdf-engine'

/** Fixtures are generated by scripts/make-pdf-fixtures.mjs from invented text (CLAUDE.md). */
const withText = join(process.cwd(), 'test', 'fixtures', 'angebot-text.pdf')
const scanned = join(process.cwd(), 'test', 'fixtures', 'angebot-scan.pdf')
const engine = new PdfEngine()

describe('PdfEngine', () => {
  it('extracts the text layer including umlauts', { timeout: 60_000 }, async () => {
    const result = await engine.extract(withText)
    const text = result.text.toLowerCase()

    expect(text).toContain('angebot')
    expect(text).toContain('münchen')
    expect(text).toContain('1.249,90')
    expect(result.pageCount).toBeGreaterThanOrEqual(2)
  })

  it('reassembles positioned fragments into readable lines', { timeout: 60_000 }, async () => {
    // pdf.js reports fragments, not lines; without grouping by vertical position a two-column
    // invoice comes out interleaved word by word.
    const result = await engine.extract(withText)
    expect(result.lines.some((l) => /küchenmöbel.*straßenweg/i.test(l.text))).toBe(true)
  })

  it(
    'tags each line with its page, so a hit can name where it was found',
    { timeout: 60_000 },
    async () => {
      const result = await engine.extract(withText)
      expect(result.lines.every((l) => typeof l.page === 'number')).toBe(true)
      expect(new Set(result.lines.map((l) => l.page)).size).toBeGreaterThan(1)
    },
  )

  it(
    'reports a page without a text layer as needing OCR rather than as empty',
    { timeout: 60_000 },
    async () => {
      // A scan is not a document with no words in it — it is a picture of words, and it belongs in
      // the OCR queue (ADR 0005 C).
      const result = await engine.extract(scanned)
      expect(result.scannedPages).toContain(1)
      expect(result.text.trim()).toBe('')
    },
  )

  it('records engine and version for re-indexing', { timeout: 60_000 }, async () => {
    const result = await engine.extract(withText)
    expect(result).toMatchObject({ source: 'pdf', engine: 'pdfjs' })
  })

  it('is always available, having no model to miss', async () => {
    expect(await engine.isAvailable()).toBe(true)
  })
})
